### ISSUE TITLE
Integrating DRAMsim2 with SimpleScalar

### ISSUE THREAD

**Issue by jagan1234** [xfrings/SimpleScalar-DRAMSim2-Interface#1]
Hi all,
I am a 2nd year ME student. I am trying to integrate SimpleScalar with DRAMsim2. I found a Git link(https://github.com/xfrings/SimpleScalar-DRAMSim2-Interface @xfrings ) for integrating the simulator. M getting error while doing make after copying "dramifc.cpp and dramifc.h" files to DRAMsim2. 

below is the error I am getting.
/*********************************************************_**/
$ make DEBUG=1
g++ -DNO_STORAGE -Wall -DDEBUG_BUILD  -O0 -g -o DRAMSim AddressMapping.o Bank.o BankState.o BusPacket.o ClockDomain.o CommandQueue.o dramifc.o IniReader.o MemoryController.o MemorySystem.o MultiChannelMemorySystem.o PrintMacros.o Rank.o SimulatorObject.o TraceBasedSim.o Transaction.o 
TraceBasedSim.o:(.data+0x0): multiple definition of `SHOW_SIM_OUTPUT'
dramifc.o:(.bss+0x0): first defined here
collect2: ld returned 1 exit status
make: *_\* [DRAMSim] Error 1
/***************************************************************/

I tried to comment the multiple definition of the "SHOW_SIM_OUTPUT", then its getting build. But the dramsim.a or dramsim.so file is not getting created as specified in the link. 

Can someone please help me out of this.

Any guidance regarding the above will be very helpful.

Thank you

**Comment by asterix** [comment]
Sorry for the very late reply. I did not have access to internet for the last 3-4 weeks. The reason you don't see a `*.a or *.so` file is because the default Makefile builds an executable named `DRAMSim`. To build the static or dynamically linkable library, use:

`make libdramsim.a` or `make libdramsim.so`.

Don't forget to comment out the line with `SHOW_SIM_OUTPUT` in `dramsimifc.cpp`.

I've corrected the documentation.

**Comment by asterix** [comment]
The above should answer the question.

**Comment by jagan1234** [comment]
Hi @xfrings ,

Thanks for your reply :)

I did the changes that u specified and got the "libdramsim.a" file. I added this file in the main directory of the simplescalar ----> "simplesim-3.0" where we have the makefile. But getting the below error during the make of simplescalar.

---

sim-outorder.c:4614: error: ‘DRAMSim_On’ undeclared (first use in this function)
sim-outorder.c:4614: error: (Each undeclared identifier is reported only once
sim-outorder.c:4614: error: for each function it appears in.)
sim-outorder.c:4617: warning: implicit declaration of function ‘dram_clock’
sim-outorder.c:4623: warning: implicit declaration of function ‘dramifc_destroy_dramsim_object’

---

I know I am missing something simple here. I am new to linux and feeling difficulties in linking the library file (libdramsim.a) to the simplescalar executable build. 

So your guidance will be very helpful.
Thank you

**Comment by asterix** [comment]
Hi,

Please go through the updated README.md which provides you additional pointers. That should help you get though for starting up SimpleScalar with DRAMSim2.

Note that I can't share the full SimpleScalar modifications here. The sample implements a major part of clocking and DRAM-CPU interface management. However, you need to take care of modifications to cache.c etc needed for full usage of this interface. The idea of this repository is to handout the interface only.

**Comment by jagan1234** [comment]
Hi @xfrings,
    I tried all the modifications and still stuck. I got the following error.
gcc `./sysprobe -flags` -DDEBUG -O0 -g -Wall   -I /home/jagan/DRAMSim2  -c sim-outorder.c
**In file included from DRAMSim2/DRAMSim.h:38,
                 from /DRAMSim2/dramifc.h:27,
                 from sim-outorder.c:75:
DRAMSim2/Callback.h:38: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘DRAMSim’
In file included from DRAMSim2/dramifc.h:27,
                 from sim-outorder.c:75:
DRAMSim2/DRAMSim.h:39: fatal error: string: No such file or directory
compilation terminated.**

This error seems to be compatibility issues integrating c and c++ code(header file that dramifc.h). I also tried compiling with -lstdc++ option, but the error got complicated. The above mentioned error is gone but the following error popped out.

**error: invalid conversion from ‘const char_’ to ‘char_’
error:   initializing argument 2 of ‘void _panic(char_, char_, int, char*, ...)’
warning: deprecated conversion from string constant to ‘char***

Kindly help me with this.

**Comment by asterix** [comment]
This is a known problem. SimpleScalar is not C++ compatible. If you want to integrate DRAMSim, then you have to first make it compatible. Our approach was to solve compiler errors as they came. Most of the fixes can be classified into 4 categories:
1. Typecasting struct pointers before assignment to conform to C++.
2. All C++ keyword usage in SimpleScalar have to be replaced. Two in specific ("class" and "xor"). Just rename them. I think "class" is used in some structs too. Rename them all.
3. Most char pointers need to be placed as const char \* and const char **.
4. Lexer corrections to be compatible with C++ in `libexo/exolex.c and exolex.l` as below:

```
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif



#ifdef __cplusplus
    while ((c = yyinput()) != '*' && c != 0)
 #else
    while ((c = input()) != '*' && c != 0)
 #endif
```

Similarly everywhere there is `input()` is used. Hope this helps.
This can seem like a daunting task at first but is pretty repetitive.
